name: Schedule-Get-OpenData

on:
  schedule: # execute every hour
    - cron: "55 * * * *"
  workflow_dispatch:

jobs:
  craw-opendata:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 11 ]

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven run Test
        run: mvn -B package --file pom.xml

      - name: Git Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: automated generate data
